name: definitivo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Se ajusta la versión del SDK para ser compatible con las dependencias
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias de Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.1
  # Se elimina la versión duplicada y se deja la más reciente
  cloud_firestore: ^5.6.12 

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
