name: definitivo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Se ajusta la versión del SDK para ser compatible con las dependencias
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias de Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0 

  # Icons
  cupertino_icons: ^1.0.8

  # NUEVO: Paquete para internacionalización y formato (fechas, números, etc.)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true